/**
 * Country name (as stored on Competition.country, coming straight from
 * API-Football/BetExplorer's own naming — e.g. "South-Korea", "Faroe-Islands")
 * -> flag emoji, for the minimalist Telegram alert format (Noaim, 2026-08-23,
 * matching Suspicious Game's country-flag-per-pick style). Maps to an ISO
 * 3166-1 alpha-2 code first, then builds the flag from Unicode regional
 * indicator symbols — one small lookup table instead of hand-typing ~200
 * flag emoji. Not exhaustive: an unmapped country just gets no flag rather
 * than a wrong one.
 */
const COUNTRY_TO_ISO2: Record<string, string> = {
  India: "IN",
  Bolivia: "BO",
  Paraguay: "PY",
  Peru: "PE",
  Ecuador: "EC",
  Venezuela: "VE",
  Brazil: "BR",
  Argentina: "AR",
  Chile: "CL",
  Colombia: "CO",
  Uruguay: "UY",
  Mexico: "MX",
  "Costa-Rica": "CR",
  Guatemala: "GT",
  Honduras: "HN",
  Panama: "PA",
  Kazakhstan: "KZ",
  Uzbekistan: "UZ",
  Turkmenistan: "TM",
  Georgia: "GE",
  Armenia: "AM",
  Greece: "GR",
  Montenegro: "ME",
  Serbia: "RS",
  Croatia: "HR",
  Slovenia: "SI",
  Slovakia: "SK",
  Hungary: "HU",
  Poland: "PL",
  Romania: "RO",
  Bulgaria: "BG",
  Albania: "AL",
  "North-Macedonia": "MK",
  "Bosnia-and-Herzegovina": "BA",
  Kosovo: "XK",
  Turkey: "TR",
  Cyprus: "CY",
  Malta: "MT",
  Estonia: "EE",
  Latvia: "LV",
  Lithuania: "LT",
  Belarus: "BY",
  Ukraine: "UA",
  Russia: "RU",
  Moldova: "MD",
  Finland: "FI",
  Sweden: "SE",
  Norway: "NO",
  Denmark: "DK",
  Iceland: "IS",
  "Faroe-Islands": "FO",
  Germany: "DE",
  France: "FR",
  Spain: "ES",
  Portugal: "PT",
  Italy: "IT",
  England: "GB",
  Scotland: "GB",
  Wales: "GB",
  "Northern-Ireland": "GB",
  Ireland: "IE",
  Netherlands: "NL",
  Belgium: "BE",
  Switzerland: "CH",
  Austria: "AT",
  Luxembourg: "LU",
  Bhutan: "BT",
  Nepal: "NP",
  Bangladesh: "BD",
  "Sri-Lanka": "LK",
  Pakistan: "PK",
  Thailand: "TH",
  Vietnam: "VN",
  Indonesia: "ID",
  Malaysia: "MY",
  Singapore: "SG",
  Philippines: "PH",
  "South-Korea": "KR",
  Japan: "JP",
  China: "CN",
  Australia: "AU",
  "New-Zealand": "NZ",
  Morocco: "MA",
  Algeria: "DZ",
  Tunisia: "TN",
  Egypt: "EG",
  Nigeria: "NG",
  Ghana: "GH",
  "South-Africa": "ZA",
  Kenya: "KE",
  Tanzania: "TZ",
  Malawi: "MW",
  Zambia: "ZM",
  Zimbabwe: "ZW",
  Uganda: "UG",
  Senegal: "SN",
  "Ivory-Coast": "CI",
  Cameroon: "CM",
  "Saudi-Arabia": "SA",
  Qatar: "QA",
  UAE: "AE",
  Israel: "IL",
  Jordan: "JO",
  Iraq: "IQ",
  Iran: "IR",
  USA: "US",
  Canada: "CA",
};

function flagFromIso2(iso2: string): string {
  return String.fromCodePoint(...[...iso2.toUpperCase()].map((c) => 127397 + c.charCodeAt(0)));
}

/** Returns "" (never a placeholder) when the country isn't in the map, so
 *  callers can just concatenate without an extra space check. */
export function countryFlagEmoji(country: string | null | undefined): string {
  if (!country) return "";
  const iso2 = COUNTRY_TO_ISO2[country];
  return iso2 ? flagFromIso2(iso2) : "";
}
